/* EJERCICIO 1*/
INSERT INTO PROFESORADO VALUES
(1, 'NURIA', 'ANERO GONZÁLEZ', '58328033X', 'MATEMÁTICAS', '22/02/1972', 9);

/* EJERCICIO 2 */
INSERT INTO PROFESORADO VALUES
(2, 'MARIA LUISA', 'FABRE BERDÚN', '51083099F', 'TECNOLOGÍA', '31/03/1975', 4);

INSERT INTO PROFESORADO (CODIGO, NOMBRE, APELLIDOS,  ESPECIALIDAD, FECHA_NAC, ANTIGUEDAD) VALUES
(3, 'JAVIER', 'JIMÉNEZ HERNANDO', 'LENGUA', '04/05/1969', 10);

INSERT INTO PROFESORADO VALUES
(4, 'ESTEFANÍA', 'FERNÁNDEZ MARTÍNEZ', '19964324W', 'INGLÉS', '22/06/1973', 5);

INSERT INTO PROFESORADO (CODIGO, NOMBRE, APELLIDOS) VALUES
(5, 'JOSE M.', 'ANERO PAYÁN');

/* EJERCICIO 2 */

UPDATE CURSOS SET COD_PROFE = 4 WHERE CODIGO = 1;
UPDATE CURSOS SET COD_PROFE = 2 WHERE CODIGO = 2;
UPDATE CURSOS SET COD_PROFE = 2 WHERE CODIGO = 3;
UPDATE CURSOS SET COD_PROFE = 1 WHERE CODIGO = 4;
UPDATE CURSOS SET COD_PROFE = 1 WHERE CODIGO = 5;
UPDATE CURSOS SET COD_PROFE = 3 WHERE CODIGO = 6;

/* EJERCICIO 4 a */

UPDATE PROFESORADO SET FECHA_NAC = '22/06/1974', ANTIGUEDAD = 4 WHERE NOMBRE = 'ESTEFANÍA';

/* EJERCICIO 4 b */
UPDATE PROFESORADO SET ESPECIALIDAD='INFORMÁTICA', DNI = '9876543C' WHERE CODIGO = 3;

/* EJERCICIO 5 a */

UPDATE PROFESORADO SET ANTIGUEDAD = ANTIGUEDAD + 1;

/* EJERCICIO 5 b */
UPDATE PROFESORADO SET ANTIGUEDAD = ANTIGUEDAD - 2 WHERE ANTIGUEDAD > 2;

/* EJERCICIO 6 */
DELETE FROM CURSOS WHERE CODIGO = 6;

/* EJERCICIO 7 - a */

DELETE FROM ALUMNADO WHERE COD_CURSO = 3;

/* EJERCICIO 7 - b */
DELETE FROM ALUMNADO WHERE SEXO = 'H' AND COD_CURSO = 2;

/* EJERCICIO 8 - a */

INSERT INTO ALUMNADO (NOMBRE, APELLIDOS, SEXO, FECHA_NAC) SELECT * FROM ALUMNADO_NUEVO;

/* EJERCICIO 9 - a */

UPDATE CURSOS SET MAX_ALUMN = (SELECT COUNT(CODIGO) FROM ALUMNADO WHERE COD_CURSO = 2) WHERE CODIGO = 2;

/* EJERCICIO 10 - a */

DELETE FROM ALUMNADO WHERE COD_CURSO IN
(SELECT CODIGO FROM CURSOS WHERE COD_PROFE = 
(SELECT CODIGO FROM PROFESORADO WHERE NOMBRE = 'NURIA'));

INSERT INTO ALUMNADO 















